- framework/OpenMod.Core/Commands/CommandContext.cs
- framework/OpenMod.Core/Commands/CommandWrongUsageException.cs
- framework/OpenMod.Core/Commands/OpenModCommands/CommandOpenModInstall.cs
- framework/OpenMod.Core/Commands/OpenModCommands/CommandOpenModUpdate.cs
- fix showing "correct" command usage when it is wrong.
Before:
.. add add <player>...
After:
.. pg add <player> ...
- fixed `om u` and `om i` when no args it throws IndexOutOfRange
> Small changes

- samples/UniversalSamplePlugin/UniversalSamplePlugin.cs
- unturned/OpenMod.Unturned/Users/UnturnedUser.cs
This ensures ChatManager.serverSendMessage() is sent from the main thread, otherwise it will error. UniversalSamplePlugin.cs is unrelated.
I am unfamiliar with UniTask, maybe it's necessary to switch back to thread pool afterwards?
Traceback:
```
[2020-06-26 15:54:01 ERR][] Exception occured in task "Player command execution"
System.NotSupportedException: This function should only be called from the game thread. (e.g. from Unity's Update)
at SDG.Unturned.ThreadUtil.assertIsGameThread () [0x0000c] in <583092d77ee44d62b65636564269a567>:0 
at SDG.Unturned.ChatManager.serverSendMessage (System.String text, UnityEngine.Color color, SDG.Unturned.SteamPlayer fromPlayer, SDG.Unturned.SteamPlayer toPlayer, SDG.Unturned.EChatMode mode, System.String iconURL, System.Boolean useRichTextFormatting) …
```
> Fix Sending Messages in Unturned

- framework/OpenMod.Core/Users/OfflineUserProvider.cs
```
Exception occured on command "balance asd" by actor console/Console (openmod-unturned-console)
System.NullReferenceException: Object reference not set to an instance of an object
at OpenMod.Core.Users.OfflineUser..ctor (OpenMod.API.Users.IUserDataStore userDataStore, OpenMod.API.Users.UserData data) [0x00007] in <405ae8bb4571464eabafde1aeb743e78>:0 
at OpenMod.Core.Users.OfflineUserProvider+<FindUserAsync>d__3.MoveNext () [0x00096] in <405ae8bb4571464eabafde1aeb743e78>:0 
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <e1319b7195c343e79b385cd3aa43f5dc>:0 
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in …
```
> Fix OfflineUserProvider when user doesn't exists

- unturned/OpenMod.Unturned/Users/UnturnedUserProvider.cs
Exception example:
```
[2020-06-29 15:07:58 WRN][SDG.Unturned] Sequence contains no matching element
[2020-06-29 15:07:58 WRN][SDG.Unturned]   at System.Linq.Enumerable.First[TSource] (System.Collections.Generic.IEnumerable`1[T] source, System.Func`2[T,TResult] predicate) [0x00011] in <fbb5ed17eb6e46c680000f8910ebb50c>:0 
at OpenMod.Unturned.Users.UnturnedUserProvider+<>c__DisplayClass12_0+<<OnRejectingPlayer>b__0>d.MoveNext () [0x00020] in <e6c488449c9044a3ab25975735fbb144>:0 
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <e1319b7195c343e79b385cd3aa43f5dc>:0 
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in …
```
> Fix some exceptions

- framework/OpenMod.Core/Commands/CommandParameters.cs
- framework/OpenMod.Core/Commands/MethodCommandWrapper.cs
- framework/OpenMod.Core/Plugins/OpenModUniversalPlugin.cs
- CS1998: This async method lacks 'await' operators and will run synchronously.
- CS4014: Because this call is not awaited, execution of the current method continues before the call is completed.
> Fix some async/await warnings

- framework/OpenMod.API/Users/IUserManager.cs
- framework/OpenMod.API/Users/IUserProvider.cs
- framework/OpenMod.Core/Users/OfflineUserProvider.cs
- framework/OpenMod.Core/Users/UserManager.cs
- unturned/OpenMod.Unturned/Users/UnturnedUserProvider.cs
Added `BroadcastAsync(string message)` and `BroadcastAsync(string userType, string message)` to `IUserProvider` and `IUserManager`.
This will allow plugins to just send a message if they chose to not deal with colors.
> Add color-less BroadcastAsync methods

- extensions/OpenMod.Extensions.Economy.Abstractions/NotEnoughBalanceException.cs
I can't understand why it says that CommandOpenModInstall.cs is different from the source
> Pass balance on NotEnoughBalanceExcetion

- framework/OpenMod.Core/Eventing/Event.cs
- framework/OpenMod.Core/Eventing/EventBus.cs
Abstract events should not be emitted. In the logs, this also gets confusing as you'll see behaviour like this:
```
[23:09:28 VRB][OpenMod.Core.Eventing.EventBus] Emitting event: OpenModInitialized
[23:09:28 VRB][OpenMod.Core.Eventing.EventBus] OpenModInitialized: No listeners found.
[23:09:28 VRB][OpenMod.Core.Eventing.EventBus] Emitting event:
[23:09:28 VRB][OpenMod.Core.Eventing.EventBus] : No listeners found.
[23:09:28 VRB][OpenMod.Core.Eventing.EventBus] Emitting event: Base
[23:09:28 VRB][OpenMod.Core.Eventing.EventBus] Base: No listeners found.
```
Also fixes moving on to the base type prematurely when emitting events.
> Fixes infinite loop and abstract events emitting

- framework/OpenMod.Core/Persistence/YamlDataStore.cs
The file system watcher is meant to watch a directory and takes such as its single parameter. To watch a single file within said directory, the filter (second param) must be the file name.
Exception is thrown without this fix as the path given is a file, not a directory.
> Fixes file system watcher within YamlDataStore

- framework/OpenMod.Core/Permissions/DefaultPermissionRoleStore.cs
if a player's permissions need to be checked before he is seeded
> Fix check player permission when user is no seeded

- unturned/OpenMod.Unturned/Building/UnturnedBarricadeBuildable.cs
- unturned/OpenMod.Unturned/Building/UnturnedStructureBuildable.cs
As discussed on discord, the destroy methods for buildables should call the manager's respective destroy methods, as otherwise no replication is done.
Fixes #199
> Fix an issue with destroying buildables in unturned

- unturned/OpenMod.Unturned/Players/Connections/Events/PlayerConnectionsEventsListener.cs
- unturned/OpenMod.Unturned/Users/UnturnedUserProvider.cs
Fixes bugs where not all Unity components are started and ready to be accessed by methods subscribing to events.
> Delayed UnturnedUser and UnturnedPlayer connected events by one frame

- framework/OpenMod.Core/Eventing/EventBus.cs
Also removes unnecessary check if base type is an interface, as `Type.BaseType` never returns an interface.
> Fixes abstract base types of events not emitting

- framework/OpenMod.Core/Commands/Parameters/TimeSpanCommandParameterResolveProvider.cs
- framework/OpenMod.Core/Helpers/TimeSpanHelper.cs
- framework/OpenMod.Core/ServiceConfigurator.cs
Also added TimeSpan parameter resolution using added parser
Examples of unparsed inputs:
- 20 seconds
- 30 days, 40 minutes, and 50 seconds
- 10h20m30s
- 3.5 days 30 seconds
- 1234.123     milliseconds
> Added standardized TimeSpan string parser

- unturned/OpenMod.Unturned/Building/Events/BuildablesEventsListener.cs
when for example a player salvage a crate from a car:
```
[2020-11-19 23:00:43 ERR][SDG.Unturned] Exception has been thrown by the target of an invocation.
[2020-11-19 23:00:43 ERR][SDG.Unturned]   at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00048] in <fb001e01371b4adca20013e0ac763896>:0 
at System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) [0x00000] in <fb001e01371b4adca20013e0ac763896>:0 
at SDG.Unturned.SteamChannel.receive (Steamworks.CSteamID steamID, System.Byte[] packet, System.Int32 offset, System.Int32 size) [0x003bd] in <d94adcdf5b0146e4b8bdbf55a4ea14c6>:0 
[2020-11-19 23:00:43 …
```
> Fix Buildables not checking plant cases and Clean up code

- framework/OpenMod.Runtime/Runtime.cs
Likely fixes other unknown problems as well which reference Runtime.IsDisposing
> Fixes permissions not reregistering after reload

- framework/OpenMod.Runtime/Runtime.cs
Error that occurs:
```
System.InvalidCastException: Specified cast is not valid.
at System.Nullable`1[T].Unbox (System.Object o) [0x0000d] in <9577ac7a62ef43179789031239ba8798>:0
at OpenMod.Runtime.Runtime+<InitAsync>d__48.MoveNext () [0x004c0] in <bbfef474430f441c83fd7dfee08b80ff>:0
Failed to initialize nexus!
Specified cast is not valid.
at System.Nullable`1[T].Unbox (System.Object o) [0x0000d] in <9577ac7a62ef43179789031239ba8798>:0
at OpenMod.Runtime.Runtime+<InitAsync>d__48.MoveNext () [0x00889] in <bbfef474430f441c83fd7dfee08b80ff>:0
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <9577ac7a62ef43179789031239ba8798>:0
at …
```
> Fixes runtime error from incorrect hot reloading config parsing

- unturned/OpenMod.Unturned/Zombies/Events/UnturnedZombieDamagingEvent.cs
- unturned/OpenMod.Unturned/Zombies/Events/UnturnedZombieDyingEvent.cs
- unturned/OpenMod.Unturned/Zombies/Events/ZombieEventsListener.cs
Should remove `DropLoot` & `TrackKill` from the event because it will be always true? Fixes #253
> Add instigator to zombie events damaging & dying

- framework/OpenMod.Core/Plugins/OpenModPluginBase.cs
- framework/OpenMod.Core/Plugins/PluginActivator.cs
Fixes #226
Also, dispose lifetimeScope when plugin it's crashed. Fixes #296 
edit: After testing i notice that event don't called
https://github.com/openmod/openmod/blob/2006282cfe032a8fbf0c8562a13fccb6d04902ff/framework/OpenMod.Core/Plugins/OpenModPluginBase.cs#L116
> Fix PluginService cannot be disposed async

- framework/OpenMod.Core/Eventing/EventBus.cs
Before => removes **first** found `Event` word
Now => removes **last** found `Event` word **if ends with it**
> Fix removing suffix from event name

- framework/OpenMod.API/OpenMod.API.csproj
While on net461 works fine, on netcoreapp3.1 throws
```
System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Bcl.AsyncInterfaces, Version=1.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.
File name: 'Microsoft.Bcl.AsyncInterfaces, Version=1.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
at OpenMod.Core.Ioc.LifetimeScopeExtensions.BeginLifetimeScopeEx(ILifetimeScope this, Action`1 configurationAction)
at OpenMod.Runtime.Runtime.InitAsync(List`1 openModHostAssemblies, RuntimeInitParameters parameters, Func`1 hostBuilderFunc) in G:\csharp\openmod\openmod\framework\OpenMod.Runtime\Runtime.cs:line 210
at OpenMod.Standalone.Program.Main(String[] args) in …
```
> Fix Microsoft.Bcl.AsyncInterfaces not found

- unturned/OpenMod.Unturned/Building/UnturnedBuildableDirectory.cs
On BaseClustering, with an almost identical code, I tested getting all buildables and was seeing a time of ~40s for 45k buildables to be returned:
After adding these 4 .ToList() and nothing else, time dropped down to 15ms for 45k buildables to be returned:
Final code in BaseClustering:
The BaseClustering I tested was RM, BUT the code used in base clustering's GetBuildables is a near identical copy of this code, and uppon running multiple stopwatch runs on the code, I realized that selecting all of the structures (and barricades) was taking too long.
After simply adding 2 ToLists() to structureData's assignment and structureDrop's, the time to select the structures enumerable (and subsequently the barricades enumerable) dropped to just ms
This should significantly speed up the method …
> Optimize buildable grouping in GetBuildablesAsync

- framework/OpenMod.Core/logging.yaml
It's a very-very strange bug. Fixes #369
> Fix logging.yaml cannot be parsed

- framework/OpenMod.Core/Helpers/AssemblyHelper.cs
- framework/OpenMod.NuGet/NuGetPackageManager.cs
- framework/OpenMod.Runtime/OpenModStartup.cs
Embedded resource `packages.yaml` must have same format as packages.yaml generated by OpenMod.
Example:
```
packages:
- id: SilK.Shops
version: 1.0.0
```
> Add functionality for packages.yaml within plugins to force install of packages

- framework/OpenMod.Core/Helpers/Retry.cs
- framework/OpenMod.Core/Persistence/YamlDataStore.cs
To reproduce:
1. Run OpenMod.Standalone
2. Edit `openmod.commands.yaml` - nothing will happen
3. Edit `openmod.commands.yaml` again - the exception will be thrown
```
[19:48:39 ERR][OpenMod.Core.Persistence.YamlDataStore] Error occured on file change for: G:\csharp\openmod\openmod\standalone\OpenMod.Standalone\bin\Debug\net461\openmod\openmod.commands.yaml
System.IO.IOException: The process cannot access the file 'G:\csharp\openmod\openmod\standalone\OpenMod.Standalone\bin\Debug\net461\openmod\openmod.commands.yaml' because it is being used by another process.
at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions …
```
> YamlDataStore: Fix "File being used by another process"

- unturned/OpenMod.Unturned/Players/UnturnedPlayer.cs
Caused by integer overflow which leads to negative damage amount. (Unturned casts `float` to `int`).
> Fix player not being killed

- framework/OpenMod.Common/Helpers/FileHelper.cs
- framework/OpenMod.Common/Helpers/StreamHelper.cs
- framework/OpenMod.Common/Hotloading/Hotloader.cs
- framework/OpenMod.Common/OpenMod.Common.csproj
- framework/OpenMod.Core/Plugins/FileSystemPluginAssembliesSource.cs
- framework/OpenMod.NuGet/NuGetPackageManager.cs
- framework/OpenMod.Runtime/Runtime.cs
Allows debugging plugins that have .pdb file next to .dll
> Load plugin's debug symbols

- unturned/OpenMod.Unturned/Resources/Events/ResourcesEventsListener.cs
- unturned/OpenMod.Unturned/Resources/Events/UnturnedResourceDamagingEvent.cs
A single event from ResourceManager
This exposes `ResourceSpawnpoint`, it should be fine since there is no resource abstraction currently or planned afaik
> Resource events

- framework/OpenMod.Core/Localization/ConfigurationBasedStringLocalizerFactory.cs
- framework/OpenMod.Runtime/Runtime.cs
- unturned/OpenMod.Unturned/OpenModUnturnedHost.cs
- Fixed performance issue with FileSystemWatcher on Unity Mono Windows
- Unturned UniTask: switched GetDefaultPlayerLoop to GetCurrentPlayerLoop
- Re-registering the change token on reload callback
> Fix performance issue with FileSystemWatcher on Mono

- unturned/OpenMod.Unturned/Players/Quests/Events/PlayerQuestsEventsListener.cs
- unturned/OpenMod.Unturned/Players/Quests/Events/UnturnedPlayerFlagChangedEvent.cs
- unturned/OpenMod.Unturned/Players/Quests/Events/UnturnedPlayerGroupChangedEvent.cs
- unturned/OpenMod.Unturned/Players/Quests/Events/UnturnedPlayerGroupRankChangedEvent.cs
This is the list of the events I added:
PlayerQuests.onGroupChanged which is fired when a player changes/leaves/destroys a group.
player.quests.groupRankChanged which is fired when a players group rank is changed.
PlayerQuests.onAnyFlagChanged which is fired when a players flag is changed.
> Added some new events for Player Quests.

- unturned/OpenMod.Unturned/Users/UnturnedUserProvider.cs
IStringLocalizer causes dependency resolution exception when creating an instance of `UserManager`.
> Fix OpenMod crash due to string localizer

- unturned/OpenMod.Unturned/Users/UnturnedUserProvider.cs
The events `OnPlayerConnected`, `OnPlayerDisconnected`, `OnRejectingPlayer`, and `OnPendingPlayerConnecting` get the user information on the main thread and stall the server. This isn't noticeable if you only have a few users in your openmod.users.yaml file, but when there are thousands of users in the file, then it will cause a massive lag spike whenever someone joins or leaves.
I've changed the event code to run on a different thread using AsyncHelper.Schedule(), and it's been working great on my servers.
I have also added the changes from #529.
> Fix stalling the server on player connect and disconnect

- docs/templates/discordfx/partials/li.tmpl.partial
> Fix docs sidebar category item formatting

- unturned/OpenMod.Unturned/Players/UnturnedPlayerCommandParameterResolveProvider.cs
Sometimes the playerName is not the same as the characterName.
> Add check by characterName on UnturnedPlayerCommandParameterResolveProvider

- framework/OpenMod.API/Eventing/IEventBus.cs
- framework/OpenMod.API/Eventing/IEventListenerOptions.cs
- framework/OpenMod.Core/Eventing/EventBus.cs
- framework/OpenMod.Core/Eventing/EventListenerAttribute.cs
- framework/OpenMod.Core/Eventing/EventSubscription.cs
Adds three new overloads to `IEventBus` to allow for manual passing of event listener options:
- `IDisposable Subscribe(IOpenModComponent, string, EventCallback, IEventListenerOptions);`
- `IDisposable Subscribe<TEvent>(IOpenModComponent, EventCallback<TEvent>, IEventListenerOptions)`
- `IDisposable Subscribe(IOpenModComponent, Type, EventCallback, IEventListenerOptions)`
> Add overloads including event listener options to IEventBus

- framework/OpenMod.Core/Eventing/EventBus.cs
- framework/OpenMod.Core/Plugins/OpenModPluginBase.cs
- framework/OpenMod.Core/Plugins/PluginStatus.cs
#588 857fb822 fixes OpenMod failing to unload when a plugin's Unload method throws an error when unloading.
Added OpenModPluginBase.Status to allow for checking of the exact status of the plugin and added some load/unload checks to allow for more robusticity when it comes to calling Load/Unload.
> Fix OpenMod crashing when plugins throws an error when unloading

- framework/OpenMod.Core/Users/UserManager.cs
Currently a bug exists where `BroadcastAsync` is only using `OfflineUserProvider`. This fixes this issue and broadcasts to all supported `IUserProvider`s instead of the first one found.
> Broadcast to all supporting providers instead of just the first

- framework/OpenMod.EntityFrameworkCore.MySql/Configurator/MySqlDbContextConfigurator.cs
Certain migrations result in EF Core's MySQL provider generate commands which are not compatible with certain MySQL server versions. This change auto-detects the server's MySQL version and use that version when generating commands for queries and migrations.
> Make MySQL provider auto-detect MySQL server version

- framework/OpenMod.NuGet/NuGetPackageManager.cs
Before this commit, if a package depends on another package in a different NuGet source, it will be unable to find the requested version of that dependency and will install the oldest one.
This commit fixes that by adding an additional `foreach (var sourceRepository in repositories)` loop.
> Fix installing packages from multiple NuGet sources

- framework/OpenMod.Core/Commands/CommandContextExtensions.cs
- framework/OpenMod.Core/Helpers/ArgumentsParser.cs
- framework/OpenMod.Core/Helpers/SmartFormatterHelper.cs
- framework/OpenMod.Core/Localization/ConfigurationBasedStringLocalizer.cs
- framework/OpenMod.Core/Permissions/DefaultPermissionCheckProvider.cs
- framework/OpenMod.Runtime/OpenModHostedService.cs
- unturned/OpenMod.Unturned/Players/UnturnedPlayer.cs
- unturned/OpenMod.Unturned/Users/UnturnedUser.cs
Using `Smart.Default` is not thread safely. So need to make 1 instance per thread (more info here: https://github.com/axuno/SmartFormat/wiki/Async-and-Thread-Safety ).
Also, with new version SmartFormat it's now include zero allocation string builders (ZString https://github.com/Cysharp/ZString ).
> Fix using static SmartFormatter. Use Zero allocation string builders

- framework/OpenMod.EntityFrameworkCore.MySql/Configurator/MySqlDbContextConfigurator.cs
Unable to generate migrations in Visual Studio due to connection string in config.yaml being a template. This PR changes the code to use the default server version specified by Pomelo.EntityFrameworkCore.MySql in the case where a connection can not be established.
> Fix being unable to generate migrations due to bad connection string

- unturned/OpenMod.Unturned/RocketMod/Economy/UconomyEconomyProvider.cs
Error sometimes thrown because certain Uconomy builds do not have the MoneyName property.
> Fix error with certain Uconomy builds where MoneyName/Symbol are null

- unturned/OpenMod.Unturned/Players/UnturnedPlayer.cs
Line wrapping at 90 characters is no longer necessary. The theoretical maximum number of characters a chat message can contain is 2048 as that's the default max string length in the network packet. The true limitation of message length shown is what can fit in two wrapped lines on the client-side, but this is independent of message length, as is shown below.
Message sent:
```
a.........b.........c.........d.........e.........f.........g.........h.........i.........j.........k.........l.........m.........n.........o.........p.........q.........r.........s.........t.........u.........v.........w.........x.........y.........z
```
Message shown:
Characters used on client: 191
Message sent:
```
<color=blue>a.........<color=red>b.........<color=yellow>c.........<color=green>d.........<color=#111 …
```
> Remove line wrapping at max 90 characters for Unturned chat messages

- unturned/OpenMod.Unturned/Items/UnturnedItemAssetCommandParameterResolveProvider.cs
- unturned/OpenMod.Unturned/ServiceConfigurator.cs
- unturned/OpenMod.Unturned/Vehicles/UnturnedVehicleAssetCommandParameterResolveProvider.cs
Allows for code such as the following:
```
var itemAsset = Context.Parameters.GetAsync<UnturnedItemAsset>(0);
var vehicleAsset = Context.Parameters.GetAsync<UnturnedVehicleAsset>(1);
```
> Add command parameter resolve providers for item and vehicle assets

- unturned/OpenMod.Unturned/Environment/Events/EnvironmentEventsListener.cs
- unturned/OpenMod.Unturned/Players/Clothing/Events/PlayerClothingEventsListener.cs
Fix environment events are not fired, [reported in discord](https://discord.com/channels/284399832385191936/663524633563103233/1012131715814273124) by @connorgillespie
Fixes `UnturnedPlayerClothingEquippedEvent` fired when clothing state was updated (e.g. quality).
> Fixes for Unturned events

- framework/OpenMod.Core/Rcon/Tcp/BaseTcpRconHost.cs
- unturned/OpenMod.Unturned/RocketMod/Rcon/RocketModRconClient.cs
Rocketmod rcon:
* Remove debug use in test cases (spamming console with windows/linux/mac) when using rcon
* Adding properly debug when received data 
All rcon types:
* Prevent and fix disposal error for rcon when user fail login in first try (it automatically disconnects at first try instead of third one)
> Last fixes for rcon

- framework/OpenMod.Core/Configuration/SchemaConstants.cs
- framework/OpenMod.Core/Permissions/PermissionRolesDataStore.cs
- framework/OpenMod.Core/Permissions/PermissionRolesSchemaGenerator.cs
- framework/OpenMod.Core/Permissions/PermissionsUtils.cs
- framework/OpenMod.Core/Persistence/YamlDataStore.cs
- framework/OpenMod.Core/ServiceConfigurator.cs
- framework/OpenMod.Core/Users/UserDataStore.cs
- framework/OpenMod.Core/Users/UsersSchemaGenerator.cs
Adds description, auto completion and validation of roles, permissions and other properties in `openmod.roles.yaml` and `openmod.users.yaml` file.
- Supports auto completion of original, negated and wildcard permissions
- Also works with roles
- Shows an error if the value is unknown / not valid
- Shows an error if a required property is missing
- Shows an error if a property is unknown
- Some properties have description
VS Code: `YAML`
Sublime Text: both `LSP` and `LSP-yaml`
Others: not tested, but need those which have support of `yaml-language-server`
- It is also compatible with json (in case OpenMod will use it in future).
- Schema files are saved in `.schemas` folder, which is hidden by default in the explorer.
- Schema files are generated on startup, or every time related data …
> Add schemas for openmod.roles.yaml and openmod.users.yaml

- unturned/OpenMod.Unturned/Players/Interacting/Events/UnturnedInteractEventsListener.cs
Fixes exception on patch:
```ini
[23:01:35 ERR][OpenMod.Harmony] Failed to patch original method null from patching type OpenMod.Unturned.Players.Interacting.Events.Patches
System.ArgumentException: Undefined target method for patch method static System.Boolean OpenMod.Unturned.Players.Interacting.Events.Patches::ServerSetBedOwnerInternal(SDG.Unturned.InteractableBed bed, System.Byte x, System.Byte y, System.UInt16 plant, SDG.Unturned.BarricadeRegion region, Steamworks.CSteamID steamID)
at HarmonyLib.PatchClassProcessor.PatchWithAttributes (System.Reflection.MethodBase& lastOriginal) [0x00047] in <2414a8eb44e8496080270436f777e942>:0
at HarmonyLib.PatchClassProcessor.Patch () [0x0006a] in <2414a8eb44e8496080270436f777e942>:0
```
> Fix invalid patch of bed claiming

- framework/OpenMod.Runtime/Runtime.cs
Fixes that throwing exception in `IServiceConfigurator.ConfigureServices` doesn't log anything.
Also, enables `SelfLog` on release builds to get runtime errors, for example sink `Serilog.Sinks.MariaDB` logs 
```
2023-04-08T11:37:11.7531756Z Unable to write 5 log events to the database due to following error: Table 'openmod.logs' doesn't exist
```
So user should create table or add argument to automatically create table.
> Fix some loggers doesn't work on startup 

- docs/devdoc/guides/getting-started.md
`dotnet -i` is no longer in use as stated in the screenshot in #705, also removed the "" from OpenMod.Templates::*
> fix: update `dotnet -i` to `dotnet install` #705

- framework/OpenMod.Core/Plugins/PluginHelpWriter.cs
Fixes #684 
I also removed the part of code that trying to add permission grant access to the command instead of to a list of permissions, but it didn't work correctly, here is the diff of how it should have been:
```diff
- kit [create|remove] [player] <name>
id: Kits.Commands.CommandKit
permissions:
+  - Kits:commands.kit: Grants access to the Kits.Commands.CommandKit command.
- Kits:commands.kit.give.other: Give the kit to another player but it will checks if another player has permission, money, etc..
- Kits:commands.kit.give.other.force: Force give the kit to another player without checks if the player has permission, money, etc..
- kit create <name> [cooldown] [cost] [money] [vehicleId]
id: Kits.Commands.CommandKitCreate
+  permissions:
+  - Kits:commands.kit.create: Grants access to …
```
> Fix subcommands with specified allowed actors doesn't print in help.md

- unturned/OpenMod.Unturned/Commands/CommandOpenModUpgrade.cs
By default, job scheduler will try to upgrade OpenMod on Sunday and if it's found update, then it does the hard reload.
For some reason, it's very unstable, so for better stability we just print the message to restart the server to apply changes.
> Disable auto hard reload on upgrade command

- framework/OpenMod.Common/Helpers/AssemblyNameEqualityComparer.cs
- framework/OpenMod.Common/Hotloading/Hotloader.cs
- framework/OpenMod.Common/OpenMod.Common.csproj
- framework/OpenMod.NuGet/NuGetAssembly.cs
- framework/OpenMod.NuGet/NuGetPackageManager.cs
- unturned/OpenMod.Unturned/RocketMod/Commands/RocketModCommandFromOpenMod.cs
And using low-level API for improving performance of hotloading.
```ini
BenchmarkDotNet=v0.13.5, OS=Windows 11 (10.0.22631.1830)
AMD Ryzen 5 1600, 1 CPU, 12 logical and 6 physical cores
[Host]     : .NET Framework 4.8.1 (4.8.9166.0), X64 RyuJIT VectorSize=256
DefaultJob : .NET Framework 4.8.1 (4.8.9166.0), X64 RyuJIT VectorSize=256
|                      Method |      Mean |     Error |    StdDev |      Gen0 |      Gen1 |     Gen2 | Allocated |
|---------------------------- |----------:|----------:|----------:|----------:|----------:|---------:|----------:|
|                  DnLibWrite | 68.020 ms | 1.0001 ms | 0.9355 ms | 4000.0000 | 1250.0000 | 125.0000 |  23.51 MB |
| AsmResolverReadAndWriteFast |  5.146 ms | 0.0774 ms | 0.0646 ms | 1843.7500 | 1117.1875 | 492.1875 |   9.15 MB |
```
> Use AsmResolver for hotloading

- framework/OpenMod.EntityFrameworkCore.MySql/Extensions/MySqlContainerBuilderExtensions.cs
- framework/OpenMod.EntityFrameworkCore/Extensions/EntityFrameworkCoreContainerBuilderExtensions.cs
Fixes the exception that throws on non-Mono runtimes
```
[10:45:49 INF][OpenMod.Runtime.OpenModHostedService] Initializing for host: Openmod Standalone v0.0.0+b482449e2623fe726bac734274e1dcd532c259d3
[10:45:49 INF][OpenMod.Runtime.OpenModHostedService] Loading plugins...
[10:45:49 ERR][OpenMod.Core.Plugins.PluginActivator] Failed to load plugin from type: Shops.ShopsPlugin in assembly: Shops-91f958, Version=2.0.5.0, Culture=neutral, PublicKeyToken=null
System.MethodAccessException: Attempt by method 'OpenMod.EntityFrameworkCore.MySql.Extensions.MySqlContainerBuilderExtensions.AddMySqlDbContextInternal(Autofac.ContainerBuilder, System.Type, System.Action`1<Microsoft.EntityFrameworkCore.DbContextOptionsBuilder>, System.Nullable`1<Microsoft.Extensions.DependencyInjection.ServiceLifetime>)' …
```
> Fix MethodAccessException when configuring EF Core DB context

- unturned/OpenMod.Unturned/RocketMod/RocketModIntegration.cs
This fixed https://github.com/openmod/openmod/issues/647 for me. 
The issue was that RocketModInitializedEvent and RocketModPluginsLoadedEvent were not being listened as openmod never finished to load so waiting for openmod to have loaded and then firing the events makes the integration to work.
> Fix rocketmod using rocketmod's permissions after reloading

- framework/OpenMod.NuGet/NuGetPackageManager.cs
For some reason, when `Rocket.Unturned` module is not installed, NuGet cannot resolve assembly after reloading OpenMod, needs investigation why
> Fix NuGet cannot resolve assembly after reloading OpenMod

- unturned/OpenMod.Unturned/Animals/Events/AnimalsEventsListener.cs
- unturned/OpenMod.Unturned/Animals/Events/UnturnedAnimalDamagingEvent.cs
- unturned/OpenMod.Unturned/Animals/Events/UnturnedAnimalDyingEvent.cs
- unturned/OpenMod.Unturned/Zombies/Events/ZombieEventsListener.cs
Fixes #721 with multiplying the damage amount with beacon damage reduction. And also removes reflection usage to get zombie region.
For animal damaging/dying events, added limb parameter and removed usage of reflection when trying to get instigator with vehicle bumper.
> Unturned event changes

- unturned/OpenMod.Unturned/Commands/CommandOpenModUpgrade.cs
Fixes when extracting module throws an exception, that causes the upgrade command to delete OpenMod module.
And some minor changes, like show the version of downloading module.
> Fix upgrade command delete OpenMod module

- framework/OpenMod.Core/Plugins/NuGet/NuGetPluginAssembliesSource.cs
Fixes https://github.com/openmod/openmod/issues/733
This PR reverts https://github.com/openmod/openmod/commit/959be82a3dde8563d5ef19f354f9ace0197704c9#diff-53f8f12e2513bf10e96af61fb03274ef7c10129e06b446be73a1956e51390826L95-R87
> Fix package manager installs the latest version of a package instead of the specified one

- framework/OpenMod.Core/Localization/SmartFormatOptions.cs
- framework/OpenMod.Core/ServiceConfigurator.cs
Before it was reusing the same `IFormatter` and `ISource`, so when a thread requesting create SmartFormatter is may cause multithreading issue.
Now each SmartFormatter has its own `IFormatter` and `ISource` and because of that `TryGet...` method was removed due to that.
> Create SmartFormatter with its own formatters and sources

- unturned/OpenMod.Unturned/Players/Input/Events/PlayerInputEventsListener.cs
> Fixed shared plugin keys states in `PlayerInputEventsListener.OnPluginKeyTick`

- framework/OpenMod.Core/Helpers/ArgumentsParser.cs
> Add check for empty last argument in `ArgumentsParser.ParseArguments()`

- framework/OpenMod.Core/openmod.translations.yaml
- unturned/OpenMod.Unturned/RocketMod/Permissions/RocketCooldownPermissionCheckProvider.cs
- unturned/OpenMod.Unturned/openmod.unturned.translations.yaml
Someone asked for this in Discord few weeks ago.
Before: 
```
This command is still on cooldown (583.43 seconds)
```
Now:
> More user-friendly time formatting

- unturned/OpenMod.Unturned/Mono/Patch_SocketTaskExtensions.cs
- unturned/OpenMod.Unturned/Patching/HarmonyExceptionHandler.cs
Patching `SocketTaskExtensions.ReceiveAsync` allows using async methods without any bugs.
> Fix mono socket async doesn't work as expected

- framework/OpenMod.Core/Configuration/YamlConfigurationExtensions.cs
- framework/OpenMod.Core/Localization/ConfigurationBasedStringLocalizer.cs
- framework/OpenMod.Core/Localization/ProxyStringLocalizer.cs
- framework/OpenMod.Runtime/OpenModStartupContext.cs
- framework/OpenMod.Runtime/Runtime.cs
- unturned/OpenMod.Unturned/Configuration/OpenModUnturnedConfiguration.cs
- unturned/OpenMod.Unturned/ConfigurationConfigurator.cs
- unturned/OpenMod.Unturned/ServiceConfigurator.cs
Note, it's only fixed on Windows, for Linux I have only added logging to see if it for some reason using the managed watcher, instead of `inotify`. Probably closes https://github.com/openmod/openmod/pull/758
And some other changes:
- `IConfigurationConfigurator` is now called once, for less overhead.
- Plugins can now get `HostBuilderContext` via `Context.DataStore["HostBuilderContext"]`.
- Obsolete `Context.Configuration` to use instead `HostBuilderContext.Configuration`.
- `IStringLocalizer` are now disposed on shutdown.
> Fix FileSystemWatcher CPU usage on Mono

- framework/OpenMod.Core/Persistence/YamlDataStore.cs
- framework/OpenMod.Core/Persistence/YamlDataStoreOptions.cs
- framework/OpenMod.Core/Persistence/YamlVector3TypeConverter.cs
- framework/OpenMod.Core/ServiceConfigurator.cs
- framework/OpenMod.Core/openmod.yaml
Closes #759 
Let's say we have a vector:
```cs
var vector3 = new System.Numerics.Vector3(1.234f, -11.05f, 100);
```
Then it'll be serialized into:
```yaml
vector:
x: 1,234
y: -11,05
z: 100
```
> Add YAML `System.Numerics.Vector3` converter

- unturned/OpenMod.Unturned/Vehicles/UnturnedVehicleState.cs
Fixes #780 
When we read Vehicle state we look for 255 at end for compatibility
> Trim extra zeros in vehicle state

- framework/OpenMod.Core/Jobs/JobScheduler.cs
Closes #435 
Used `TimeSpanHelper` to parse delay.
Feature works fine on standalone.
> Delay a job on startup

- docs/userdoc/concepts/jobs.md
My bad, seems like tables are not converted to html properly after last PR. I probably forgot to add extra line between text and table in markdown file. Just like here: https://github.com/openmod/openmod/blob/075c0dc4de6631e199ae5f9ed763708453011ce1/docs/devdoc/concepts/services.md?plain=1#L110C1-L115
New markdown file should be converted properly. Tested it out with https://markdowntohtml.com/
> Strange tables format at documentation 

- framework/OpenMod.Core/Localization/ConfigurationBasedStringLocalizer.cs
Format string with localizer even if the key is not found.
There is no easy way to access to SmartFormatter when using OM abstraction.
When plugins need to log info it doesnt use SmartFormatter so a alternative way is using IStringLocalizer.
`logger.LogInformation()`
> Format localizer string even when not found

- framework/OpenMod.API/Jobs/JobTask.cs
- framework/OpenMod.Core/Jobs/JobScheduler.cs
- framework/OpenMod.Core/Jobs/OpenModCommandTaskExecutor.cs
Closes #350 
Used `IEventBus.Subscribe(IOpenModComponent component, string eventName, EventCallback callback)` for subscription to events, which allows to be not bothered about event listener lifetime.
And `SmartFormatter` for parsing commands such as `command {Event.Player.Id}`. 
---
For testing I created example event class with two properties to access from command:
```cs
public sealed class ExampleEvent : Event
{
public string Message { get; }
public ulong PlayerId { get; }
public ExampleEvent(string message, ulong playerId)
{
Message = message;
PlayerId = playerId;
}
}
```
Job configuration in `autoexec.yaml` looks as further:
```yaml
jobs:
- name: Test Event Job
args:
commands:
- test_event_command {Event.Message} and {Event.PlayerId}
task: openmod_command
schedule: '@event:Example' …
```
> Jobs on event emitted

- unityengine/OpenMod.UnityEngine/Helpers/TlsCertValidationWorkaround.cs
- unityengine/OpenMod.UnityEngine/Helpers/TlsHandshakeWorkaround.cs
- unityengine/OpenMod.UnityEngine/Helpers/ValidationHelper.cs
- unityengine/OpenMod.UnityEngine/UnityHostLifetime.cs
Fixes https://github.com/openmod/openmod/issues/816
> Fix UNITYTLS_X509VERIFY_NOT_DONE is thrown on server

- unityengine/OpenMod.UnityEngine/Helpers/TlsCertValidationWorkaround.cs
- unityengine/OpenMod.UnityEngine/Helpers/TlsHandshakeWorkaround.cs
- unityengine/OpenMod.UnityEngine/ServiceConfigurator.cs
- unityengine/OpenMod.UnityEngine/UnityHostLifetime.cs
Refactored those classes to be registered as hosted services to avoid statics. I hope this won't break something again
> Fix Harmony unpatches globally and correctly unsubscribe from `ServerCertificateValidationCallback`

- unturned/redist/OpenMod.Unturned.Redist.nuspec
Since unturned bootstrap targets net48, we need unturned redist to do the same
> Update Unturned to also target net48

- docs/devdoc/events/unturned.md
The UnturnedPlayerDroppedItemEvent is cancellable
> UnturnedPlayerDroppedItemEvent Cancellable
