README.md
=> Fix README rm4 to RM4

framework/OpenMod.API/Users/IUser.cs, unturned/OpenMod.Unturned/Users/UnturnedPendingUser.cs, unturned/OpenMod.Unturned/Users/UnturnedUser.cs
Change kick reason from null to the empty string, because it may be throw NullReferenceException
=> Change reason kick

README.md
The title says it all. Paper is bad.
=> Fix seperate to separate

framework/OpenMod.Core/Helpers/AssemblyHelper.cs
For issue: https://github.com/openmod/OpenMod/issues/22
I have not been able to test yet but it should be a good start.
=> Resource Updating

framework/OpenMod.Core/Commands/OpenModCommands/CommandHelp.cs
=> Fix Help Command Page Count

standalone/OpenMod.Standalone/StandaloneConsoleIo.cs, unturned/OpenMod.Unturned/OpenModUnturnedHost.cs
- Added .Trim
- Use another event on shutdown
=> Small changes

framework/OpenMod.Core/Commands/OpenModComponentCommandSource.cs, unturned/OpenMod.Unturned/Permissions/UnturnedAdminPermissionCheckProvider.cs
=> Fix ReflectionTypeLoadException on ScanAssemblyForCommmmands

framework/OpenMod.Core/Commands/CommandStore.cs, framework/OpenMod.Core/Eventing/EventBus.cs, framework/OpenMod.Core/Permissions/PermissionChecker.cs, framework/OpenMod.Core/Users/UserManager.cs, unturned/OpenMod.Unturned/OpenModUnturnedHost.cs, unturned/OpenMod.Unturned/Users/UnturnedUserProvider.cs
Fixes #92.
I will try also to check why `UserManager` and etc.. are disposing of twice
=> Fix UnturnedUserProvider is not disposing

framework/OpenMod.Core/Persistence/YamlDataStore.cs
Fixes saving false Booleans and potentially other serialization errors. Tested and working.
=> Emit Defaults

framework/OpenMod.Core/Commands/CommandExecutor.cs, framework/OpenMod.Core/Helpers/ArgumentsParser.cs, standalone/OpenMod.Standalone/StandaloneHost.cs, unturned/OpenMod.Unturned/OpenModUnturnedHost.cs, unturned/OpenMod.Unturned/Users/UnturnedCommandHandler.cs
=> Fix invalid spaces on command

props/SharedProjectProps.props
=> Fix SDK import warnings

framework/OpenMod.Bootstrapper/OpenModDynamicBootstrapper.cs, framework/OpenMod.Core/Helpers/ArgumentsParser.cs, framework/OpenMod.Core/Plugins/PluginAssemblyStore.cs, unturned/OpenMod.Unturned.Module.Dev/OpenModUnturnedModule.cs, unturned/OpenMod.Unturned.Module.Shared/OpenModSharedUnturnedModule.cs, unturned/OpenMod.Unturned.Module/OpenModUnturnedModule.cs
=> Fix module detection

extensions/OpenMod.Extensions.Games.Abstractions/Buildings/IBuildable.cs, extensions/OpenMod.Extensions.Games.Abstractions/Buildings/IBuildableAsset.cs, extensions/OpenMod.Extensions.Games.Abstractions/Buildings/IBuildableDirectory.cs, extensions/OpenMod.Extensions.Games.Abstractions/Buildings/IBuildableState.cs, extensions/OpenMod.Extensions.Games.Abstractions/Buildings/IOwnership.cs, unturned/OpenMod.Unturned/Buildings/UnturnedBarricadeBuildable.cs, unturned/OpenMod.Unturned/Buildings/UnturnedBuildableAsset.cs, unturned/OpenMod.Unturned/Buildings/UnturnedBuildableOwnership.cs, unturned/OpenMod.Unturned/Buildings/UnturnedBuildableState.cs, unturned/OpenMod.Unturned/Buildings/UnturnedStructureBuildable.cs
Includes a basic implementation on the unturned end, which has to be finished.
=> Initial abstraction of buildables

framework/OpenMod.Core/Commands/CommandStore.cs
https://hastebin.com/ubajamirin.cs
Fixing this problem
=> Fix exception on shutdown

standalone/OpenMod.Standalone/StandaloneHostInformation.cs
Standalone not working without a host information
=> Add Standalone host information

unturned/OpenMod.Unturned/Items/UnturnedItemSpawner.cs
=> Remove duplicate give

unturned/OpenMod.Unturned/Building/Events/BuildablesEventsListener.cs, unturned/OpenMod.Unturned/Building/Events/UnturnedBarricadeTransformedEvent.cs, unturned/OpenMod.Unturned/Building/Events/UnturnedBarricadeTransformingEvent.cs, unturned/OpenMod.Unturned/Building/Events/UnturnedBuildableTransformedEvent.cs, unturned/OpenMod.Unturned/Building/Events/UnturnedBuildableTransformingEvent.cs, unturned/OpenMod.Unturned/Building/Events/UnturnedStructureTransformedEvent.cs, unturned/OpenMod.Unturned/Building/Events/UnturnedStructureTransformingEvent.cs
Fixed a missing unsubscriptions from events from Unsubscribe (destroy events)
Added all related events to buildable transforming and their related hooks.
Added 2 PostFix patches to support post-transformed.
=> Added Buildable Transform related Events (Unturned)

unturned/rocketmod/Rocket.API/Rocket.API.csproj, unturned/rocketmod/Rocket.Core/Rocket.Core.csproj, unturned/rocketmod/Rocket.PermissionLink/Rocket.PermissionLink.csproj, unturned/rocketmod/Rocket.Unturned/Player/UnturnedPlayer.cs, unturned/rocketmod/Rocket.Unturned/Rocket.Unturned.csproj, unturned/rocketmod/Rocket.Unturned/RocketUnturnedOpenModPlugin.cs, unturned/rocketmod/Rocket.Unturned/U.cs
* Update Rocket bridge and perm link to last om version
* Update Rocket bridge to same version as LDM (fixing IP issue)
* Fix issues related with rocket bridge doesnt reload properly
Related issues (fix with this pr):
https://github.com/openmod/openmod/issues/232
https://github.com/openmod/openmod/issues/233
=> Fix rocket bridge and update

unturned/rocketmod/Rocket.Unturned/Environment.cs
=> Fix issue #241

framework/OpenMod.Core/Commands/CommandDataStore.cs
Found issue: Sometimes throws IOException sharing violation on path ->
Fixed: Saving file on dispose, like UserDataStore.
=> Fix openmod.commands.yaml is empty after shutdown server

framework/OpenMod.NuGet/NuGetPackageManager.cs
=> Dispose PackageArchiveReader

rust/OpenMod.Rust/OpenMod.Rust.csproj, rust/oxide/OpenMod.Rust.Oxide.Extension.Dev/OpenMod.Rust.Oxide.Extension.Dev.csproj, rust/oxide/OpenMod.Rust.Oxide.Extension/OpenMod.Rust.Oxide.Extension.csproj, rust/oxide/OpenMod.Rust.Oxide/OpenMod.Rust.Oxide.csproj, unityengine/OpenMod.UnityEngine/OpenMod.UnityEngine.csproj, unturned/OpenMod.Unturned.Module.Shared/OpenMod.Unturned.Module.Shared.csproj, unturned/OpenMod.Unturned.Module/OpenMod.Unturned.Module.csproj, unturned/OpenMod.Unturned/OpenMod.Unturned.csproj
=> Do not copy redist assemblies to output

framework/OpenMod.Core/Permissions/PermissionRolesDataStore.cs
Cannot test it because on DEV module version SystemFileWatcher for me not working
=> Add FileWatcher to PermissionRolesDataStore

framework/OpenMod.Core/Persistence/YamlDataStore.cs
Closes #272. If still will be YamlDataStore then can be merged PR. I love YAML but why switching to JSON? :(
=> Fix suffix is not set to file

framework/OpenMod.Core/Plugins/PluginHelpWriter.cs
Removes some white spaces. Fixes command writes wrong if parent command has many child commands. Optimize StringBuilder
Before:
```
Id:  Dummy  
Version:  0.0.0  
Author: -------
Website: https://discord.gg/------
- dummy  
id: Dummy.Commands.CommandDummy  
- dummy stance <id> <stance>  
id: Dummy.Commands.Actions.CommandDummyStance  
- dummy stance <id> <inputFieldName> <text>  
id: Dummy.Commands.Actions.CommandDummyInputText  
- dummy stance <id> <gesture>: Make a dummy gesture  
id: Dummy.Commands.Actions.CommandDummyGesture  
- dummy stance <id> <face>: Send a face to dummy  
id: Dummy.Commands.Actions.CommandDummyFace  
- dummy stance <id> <command>: Execute a command by Dummy  
id: Dummy.Commands.Actions.CommandDummyExecute  
- dummy stance <id> <buttonName>  
id: …
```
=> Fix PluginHelpWriter

unturned/OpenMod.Unturned/OpenModUnturnedHost.cs, unturned/OpenMod.Unturned/Plugins/OpenModPluginsBroadcaster.cs
=> Update plugins list on plugin load/unload

unturned/OpenMod.Unturned/Building/Events/BuildablesEventsListener.cs
Don't merge just yet - still needs testing. I'll test the fix later.
=> Fixes exception in AskTransformBarricade

framework/OpenMod.Core/Commands/OpenModCommands/CommandHelp.cs
https://github.com/openmod/openmod/pull/290 this PR broke it
=> Fix command help not showing child commands

unturned/OpenMod.Unturned/Commands/CommandOpenModUpgrade.cs, unturned/OpenMod.Unturned/ServiceConfigurator.cs
- Added check to compare versions
- Ignore some files
- Closes #323
=> Fix upgrade command not working

unturned/OpenMod.Unturned.Module.Dev/OpenMod.Unturned.Module.Dev.csproj, unturned/OpenMod.Unturned.Module/OpenMod.Unturned.Module.csproj
Done in https://github.com/openmod/openmod/pull/269
=> Remove outdated todo comment

unityengine/OpenMod.UnityEngine/UnityHostLifetime.cs
=> Fix CTRL + C doesn't shutdown Unturned server

standalone/OpenMod.Standalone/Program.cs
Same as https://github.com/openmod/openmod/issues/186 but for OpenMod.Standalone
=> Fix working directory for standalone

.github/actions/nuget-pack/action.yaml, .github/actions/project-build/action.yaml, .github/workflows/OpenMod.API.yaml, .github/workflows/OpenMod.Analyzers.yaml, .github/workflows/OpenMod.Bootstrapper.yaml, .github/workflows/OpenMod.Common.yaml, .github/workflows/OpenMod.Core.yaml, .github/workflows/OpenMod.EntityFrameworkCore.yaml, .github/workflows/OpenMod.Extensions.Economy.Abstractions.yaml, .github/workflows/OpenMod.Extensions.Games.Abstractions.yaml, .github/workflows/OpenMod.NuGet.yaml, .github/workflows/OpenMod.Release.yaml, .github/workflows/OpenMod.Runtime.yaml, .github/workflows/OpenMod.Rust.Oxide.Extension.yaml, .github/workflows/OpenMod.Rust.Oxide.PermissionLink.yaml, .github/workflows/OpenMod.Rust.Oxide.yaml, .github/workflows/OpenMod.Rust.yaml, .github/workflows/OpenMod.Standalone.yaml, .github/workflows/OpenMod.Templates.yaml, .github/workflows/OpenMod.UnityEngine.yaml, .github/workflows/OpenMod.Unturned.Module.yaml, .github/workflows/OpenMod.Unturned.yaml, .github/workflows/documentation.yaml
=> Fix actions

framework/OpenMod.Core/Commands/OpenModCommands/CommandHelp.cs
Fixes #376.
Also, fix command structure print
Before:
```
[00:45:52 INF][OpenMod.Core.Console.ConsoleActor] Usage: role <add/remove> <[p]layer | [r]ole> <name> <role>
[00:45:52 INF][OpenMod.Core.Console.ConsoleActor] Aliases: r, permissionrole, pr
[00:45:52 INF][OpenMod.Core.Console.ConsoleActor] Description: Manage permission roles
[00:45:52 INF][OpenMod.Core.Console.ConsoleActor] Permission: OpenMod.Core:commands.role
[00:45:52 INF][OpenMod.Core.Console.ConsoleActor] Command structure:
[00:45:52 INF][OpenMod.Core.Console.ConsoleActor] ┗ role: Manage permission roles
[00:45:52 INF][OpenMod.Core.Console.ConsoleActor]  ┣ remove
[00:45:52 INF][OpenMod.Core.Console.ConsoleActor]  ┃ ┗ removes: ONLY FOR TESTING
[00:45:52 INF][OpenMod.Core.Console.ConsoleActor]  ┃  ┗ removess: ONLY FOR TESTING …
```
=> Fix help command

unturned/OpenMod.Unturned/RocketMod/RocketModPluginsLoadedEventListener.cs
=> Fix ShimmysAdminTools RocketMod plugin override all delegates

docs/userdoc/concepts/cooldowns.md, framework/OpenMod.Core/Cooldowns/CommandCooldownStore.cs, framework/OpenMod.Core/Cooldowns/CooldownRecords.cs, framework/OpenMod.Core/Permissions/ComponentLoadedEventListener.cs, framework/OpenMod.Core/Permissions/RegisterPermissionAttribute.cs, framework/OpenMod.Core/openmod.yaml
Added attribute-based permission registrations
Cooldowns changes:
- Fixes cooldowns immunity permission not being registered.
- Added cooldowns user docs.
- Added cooldowns persistence between reloads/restarts.
=> Register permission attribute addition and cooldown fixes/features

extensions/OpenMod.Extensions.Games.Abstractions/Items/ItemDirectoryExtensions.cs, extensions/OpenMod.Extensions.Games.Abstractions/Vehicles/IVehicleAsset.cs, extensions/OpenMod.Extensions.Games.Abstractions/Vehicles/VehicleDirectoryExtensions.cs, extensions/OpenMod.Extensions.Games.Abstractions/Vehicles/VehicleSpawnerExtensions.cs, framework/OpenMod.API/Commands/ICommandParameters.cs, framework/OpenMod.Core/Helpers/StringHelper.cs, unturned/OpenMod.Unturned/Vehicles/UnturnedVehicleAsset.cs
Implemented non-exact matching of item assets and FindByIdAsync method for IVehicleDirectory.
=> Game abstractions directory extensions

extensions/OpenMod.Extensions.Games.Abstractions/IGameHostInformation.cs, extensions/OpenMod.Extensions.Games.Abstractions/KnownGameCapabilities.cs, extensions/OpenMod.Extensions.Games.Abstractions/Players/IPlayer.cs, rust/OpenMod.Rust/Players/RustPlayer.cs, rust/OpenMod.Rust/RustHostInformation.cs, unturned/OpenMod.Unturned/Players/UnturnedPlayer.cs, unturned/OpenMod.Unturned/UnturnedHostInformation.cs
For Rust, I don't know how to get the IP of a player.
=> Add IP property of player and server to game abstarctions

.github/workflows/OpenMod.Templates.yaml
=> Fix workflows replace version in plugin templates

unturned/OpenMod.Unturned/Items/UnturnedItemSpawner.cs, unturned/OpenMod.Unturned/Players/UnturnedPlayer.cs
Because invoking RPCs by name will be removed.
See https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/2432
=> Replace RPC invocations

framework/OpenMod.Core/Persistence/YamlDataStore.cs
Fixes https://github.com/openmod/openmod/issues/408
=> YamlDataStore fixes

docs/devdoc/events/unturned.md, unturned/OpenMod.Unturned/Players/Skills/Events/PlayerSkillsEventsListener.cs, unturned/OpenMod.Unturned/Players/Skills/Events/UnturnedPlayerReputationUpdatedEvent.cs, unturned/OpenMod.Unturned/Players/Voice/Events/PlayerVoiceEventsListener.cs, unturned/OpenMod.Unturned/Players/Voice/Events/UnturnedPlayerRelayVoiceEvent.cs, unturned/OpenMod.Unturned/Players/Voice/Events/UnturnedPlayerTalkingUpdatedEvent.cs
I have added 3 events, 1 for reputation and 2 for skills, I also added them to the docs including the safety updated one
=> Add Events

unturned/OpenMod.Unturned/Zombies/Events/UnturnedZombieDamagingEvent.cs, unturned/OpenMod.Unturned/Zombies/Events/UnturnedZombieDyingEvent.cs, unturned/OpenMod.Unturned/Zombies/Events/ZombieEventsListener.cs
I saw DiFFoZ tell to add these things on https://github.com/openmod/openmod/issues/465
=> Add ELimb to DyingEvent and DamagingEvent

unturned/OpenMod.Unturned/Workshop/Events/WorkshopEventsListener.cs
Removed patching in favor of serverside callback that actually works
=> Fixed UnturnedWorkshopLoadedEvent

framework/OpenMod.NuGet/NuGetPackageManager.cs
This occurs when the version range has an exclusive bound. The package manager previously would attempt to install the upper bound as it had no check for whether or not the bound was exclusive rather than inclusive.
By getting all package versions, the package manager will always install the best-matched version.
=> Fixes NuGetPackageManager installing out of range versions

unturned/OpenMod.Unturned/RocketMod/Economy/UconomyEconomyProvider.cs
=> UconomyEconomyProvider: Fix Currency symbol and name throws an error

framework/OpenMod.Core/OpenMod.Core.csproj
Contrib.Bcl.Ranges GitHub repo: https://github.com/slang25/csharp-ranges-compat
Ranges docs:
- https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-8#indices-and-ranges
- https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/tutorials/ranges-indexes
=> Add Contrib.Bcl.Ranges to OpenMod.Core

unturned/OpenMod.Unturned/Animals/Events/AnimalsEventsListener.cs, unturned/OpenMod.Unturned/Animals/Events/UnturnedAnimalDamagingEvent.cs, unturned/OpenMod.Unturned/Animals/Events/UnturnedAnimalDyingEvent.cs
=> Add instigator to UnturnedAnimalDamagingEvents

rust/OpenMod.Rust/Building/RustBuildingBlockState.cs, rust/OpenMod.Rust/Items/RustItemContainerInventory.cs, unityengine/OpenMod.UnityEngine/Transforms/UnityTransform.cs
=> Fixed the null operators bypasses the unity lifetime check

unturned/OpenMod.Unturned/Building/Events/BuildablesEventsListener.cs, unturned/OpenMod.Unturned/Building/Events/UnturnedBarricadeDeployingEvent.cs, unturned/OpenMod.Unturned/Building/Events/UnturnedBuildableDeployingEvent.cs, unturned/OpenMod.Unturned/Building/Events/UnturnedPlantHarvestingEvent.cs, unturned/OpenMod.Unturned/Building/Events/UnturnedSignModifyingEvent.cs, unturned/OpenMod.Unturned/Building/Events/UnturnedStorageOpeningEvent.cs, unturned/OpenMod.Unturned/Building/Events/UnturnedStructureDeployingEvent.cs
buildable deploying, harvesting plant, modifying sign, opening storage
=> Added missing buildable events

extensions/OpenMod.Extensions.Games.Abstractions/Building/IBuildableDeployedEvent.cs, extensions/OpenMod.Extensions.Games.Abstractions/Building/IBuildableDeployingEvent.cs, extensions/OpenMod.Extensions.Games.Abstractions/Building/IBuildableDestroyedEvent.cs, extensions/OpenMod.Extensions.Games.Abstractions/Building/IBuildableDestroyingEvent.cs, extensions/OpenMod.Extensions.Games.Abstractions/Building/IBuildableTransformedEvent.cs, extensions/OpenMod.Extensions.Games.Abstractions/Building/IBuildableTransformingEvent.cs, unturned/OpenMod.Unturned/Building/Events/UnturnedBuildableDeployedEvent.cs, unturned/OpenMod.Unturned/Building/Events/UnturnedBuildableDeployingEvent.cs, unturned/OpenMod.Unturned/Building/Events/UnturnedBuildableDestroyedEvent.cs, unturned/OpenMod.Unturned/Building/Events/UnturnedBuildableDestroyingEvent.cs, unturned/OpenMod.Unturned/Building/Events/UnturnedBuildableTransformedEvent.cs, unturned/OpenMod.Unturned/Building/Events/UnturnedBuildableTransformingEvent.cs
Following events are now universal under game abstractions:
- IBuildableDeployedEvent
- IBuildableDeployingEvent
- IBuildableDestroyedEvent
- IBuildableDestroyingEvent
- IBuildableTransformedEvent
- IBuildableTransformingEvent
=> Universal buildable events

unturned/OpenMod.Unturned.Module.Shared/OpenModSharedUnturnedModule.cs
uScript should not cause problems with openmod
=> Add uScript to the compatible modules

framework/OpenMod.API/Users/BanData.cs, framework/OpenMod.API/Users/UserData.cs, framework/OpenMod.Core/Users/OfflineUserProvider.cs, framework/OpenMod.Core/Users/UserDataSeeder.cs, framework/OpenMod.Core/Users/UserDataStore.cs, framework/OpenMod.Core/Users/UserManager.cs, framework/OpenMod.Core/openmod.translations.yaml, unturned/OpenMod.Unturned/Players/Bans/Events/BansEventsListener.cs, unturned/OpenMod.Unturned/Users/UnturnedUserProvider.cs
Added support for banning offline users
=> Ban offline users

framework/OpenMod.Core/Users/OfflineUserProvider.cs
Same thing as #527 but with `OfflineUserProvider`
=> Fixed crash due to another string localizer resolution exception

unturned/OpenMod.Unturned/Commands/UnturnedCommand.cs
=> Remove OpenModInternal attribute on UnturnedCommand

rust/OpenMod.Rust/BaseOpenModRustHost.cs, unityengine/OpenMod.UnityEngine/Helpers/TlsWorkaround.cs, unityengine/OpenMod.UnityEngine/UnityHostLifetime.cs, unturned/OpenMod.Unturned/OpenModUnturnedHost.cs
=> Add UniTask exception handler

framework/OpenMod.NuGet/Helpers/PackageArchiveReaderExtensions.cs, framework/OpenMod.NuGet/NuGetPackageManager.cs
Fixes https://github.com/openmod/openmod/issues/552
=> Fix .pdb files from nuget packages doesn't load

framework/OpenMod.API/Eventing/EventListenerPriority.cs
=> typo at OpenMod.API.Eventing.EventListenerPriority

framework/OpenMod.NuGet/NuGetPackageManager.cs
When i removed the blacklist for my old plugins that were accepted i forgot to remove me from the publisher blacklist
=> Unblacklist FPlugins from NugetPackageManager

unturned/OpenMod.Unturned/Effects/UnturnedUIEffectsKeysProvider.cs
If a plugin reserves keys, releases them, and repeats this cycle - when the component's lifetime scope finally disposes it causes the logs to be spammed with "Component ___ unloaded. Releasing all keys" despite no keys being reserved.
=> Fixed CurrentScopeEnding subscription persisting through release of all Unturned keys

framework/OpenMod.Core/Eventing/EventBus.cs
When an event is emitted and the lifetime scope has ended, an exception occurs stating a child scope cannot be created from a disposed scope. By removing the scope's subscriptions when it ends, an event will never attempt to emit with a disposed scope.
This occurs *sometimes* on OpenMod reload leaving OpenMod in a state of reloading, unable to complete but unable to run more commands as the lifetime scopes have been disposed.
These fixes make the event bus more versatile and fix this issue.
=> Fixed OpenMod reloading failing sometimes, requiring a server restart

unturned/OpenMod.Unturned/Items/UnturnedPlayerInventory.cs
thanks to Paradox for clear inventory paste)))))))
not sure how you wna redesign as it implements a read only collection /s
=> Unturned: Override Equals and implement Clear inventory enumerable

framework/OpenMod.Common/Helpers/ReflectionExtensions.cs, framework/OpenMod.Core/Eventing/EventBus.cs, framework/OpenMod.Core/Ioc/ServiceRegistrationHelper.cs, framework/OpenMod.Runtime/OpenModStartup.cs, framework/OpenMod.Runtime/Runtime.cs, unturned/OpenMod.Unturned/Users/UnturnedCommandHandler.cs
Splitting service registration causing AutoFac to dispose implementation and service interface twice
=> Combine implementation and interfaces types services into one service registration

unturned/OpenMod.Unturned/ServiceConfigurator.cs
Fixes https://github.com/openmod/openmod/issues/593
=> Fixes openmod ignoring the usage of only rocketmod permissions system

framework/OpenMod.Core/Plugins/OpenModPluginBase.cs, unturned/OpenMod.Unturned/RocketMod/Commands/RocketModCommandEventListener.cs, unturned/OpenMod.Unturned/RocketMod/Commands/RocketModCommandFromOpenMod.cs, unturned/OpenMod.Unturned/RocketMod/Commands/RocketModExecuteCommandEventTrigger.cs, unturned/OpenMod.Unturned/RocketMod/RocketModIntegration.cs, unturned/OpenMod.Unturned/RocketMod/RocketModPluginsLoadedEventListener.cs
Fixes for #619 .
When rocketmod integration is on, it will call OnExecuteCommand when a Openmod or vanilla command is executed
=> Fix for 619

framework/OpenMod.Core/Eventing/EventBus.cs
=> Lock event subscriptions list

unturned/OpenMod.Unturned/Commands/UnturnedBuiltinCommand.cs, unturned/OpenMod.Unturned/Commands/UnturnedCommandRegistration.cs, unturned/OpenMod.Unturned/RocketMod/Commands/RconPlayer.cs, unturned/OpenMod.Unturned/RocketMod/Commands/RocketModCommandEventListener.cs, unturned/OpenMod.Unturned/RocketMod/Commands/RocketModExecuteCommandEventTrigger.cs, unturned/OpenMod.Unturned/RocketMod/Permissions/OpenModPlayerPermissionActorWrapper.cs, unturned/OpenMod.Unturned/RocketMod/Rcon/NewLineType.cs, unturned/OpenMod.Unturned/RocketMod/Rcon/RocketModRconClient.cs, unturned/OpenMod.Unturned/RocketMod/Rcon/RocketModRconPacket.cs
This changes should fix https://github.com/openmod/openmod/issues/621
=> Fix rcon cmd executer

unturned/OpenMod.Unturned/Players/UnturnedPlayer.cs
before fix, this method takes food instead of health for calculating
Closes #638
=> Hot bug fix in UnturnedPlayer class, method SetHealthAsync

unturned/OpenMod.Unturned/Players/Movement/Events/PlayerMovementEventsListener.cs, unturned/OpenMod.Unturned/Players/Movement/Events/UnturnedPlayerJumpedEvent.cs
=> Add `UnturnedPlayerJumped` event

unturned/OpenMod.Unturned/RocketMod/Rcon/RocketModRconClient.cs
First packet is the negotiation and before this change it will auto assume that communication is from a mac. 
After the fisrt package, om didn't trim end line terminator.
=> Fix Rocketmod Rcon

unturned/OpenMod.Unturned.Module.Bootstrapper/OpenMod.Unturned.Module.Bootstrapper.csproj, unturned/OpenMod.Unturned.Module.Shared/OpenMod.Unturned.Module.Shared.csproj, unturned/OpenMod.Unturned.Module/OpenMod.Unturned.Module.csproj, unturned/OpenMod.Unturned/Items/UnturnedItemDrop.cs, unturned/OpenMod.Unturned/OpenMod.Unturned.csproj
Update 3.22.16
Rename SendTakeItem to SendDestroyItem and add a bool parameter to play sound effect
=> Update dist lib and fix reflection

unturned/OpenMod.Unturned/RocketMod/Rcon/RocketModRconClient.cs, unturned/OpenMod.Unturned/RocketMod/Rcon/RocketModRconPacket.cs
=> Rework rocketmod rcon support

.github/workflows/codeql-analysis.yaml, .lgtm.yml, README.md, framework/OpenMod.NuGet/NuGetPackageManager.cs, unturned/OpenMod.Unturned/Building/Events/BuildablesEventsListener.cs
[LGTM.com will be shutdown in December](https://github.blog/2022-08-15-the-next-step-for-lgtm-com-github-code-scanning/). So we should use updated CodeQL.
=> Remove LGTM. Update CodeQL workflow

unturned/OpenMod.Unturned/Players/Life/Events/PlayerLifeEventsListener.cs, unturned/OpenMod.Unturned/Players/Life/Events/UnturnedPlayerFallDamagingEvent.cs
could be a small problem cuz Im using here old version of Unturned Redist (#652)
=> add event when player getting damaged when falling

framework/OpenMod.API/Jobs/JobTask.cs, framework/OpenMod.API/OpenMod.API.csproj, framework/OpenMod.Common/Helpers/ReflectionExtensions.cs, framework/OpenMod.Core/Configuration/YamlConfigurationProviderEx.cs, framework/OpenMod.Core/Eventing/EventBus.cs, framework/OpenMod.Core/Localization/ConfigurationBasedStringLocalizer.cs, framework/OpenMod.Core/Persistence/YamlDataStore.cs, framework/OpenMod.Core/Plugins/PluginAssemblyStore.cs, framework/OpenMod.EntityFrameworkCore/ConfigurationBasedConnectionStringAccessor.cs, framework/OpenMod.Runtime/Runtime.cs, unturned/OpenMod.Unturned.Module.Bootstrapper/OpenMod.Unturned.Module.Bootstrapper.csproj, unturned/OpenMod.Unturned.Module.Shared/OpenMod.Unturned.Module.Shared.csproj, unturned/OpenMod.Unturned.Module/OpenMod.Unturned.Module.csproj, unturned/OpenMod.Unturned/Commands/CommandOpenModUpgrade.cs, unturned/OpenMod.Unturned/Locations/UnturnedLocationDirectory.cs, unturned/OpenMod.Unturned/OpenMod.Unturned.csproj, unturned/OpenMod.Unturned/RocketMod/Rcon/RconStartListener.cs, unturned/OpenMod.Unturned/RocketMod/RocketModPluginsLoadedEventListener.cs, unturned/OpenMod.Unturned/ServiceConfigurator.cs, unturned/OpenMod.Unturned/Users/UnturnedCommandHandler.cs, unturned/OpenMod.Unturned/Zombies/Events/ZombieEventsListener.cs
Fix #658 
Fix #660 
Fix #661 
Update Semver and fix obsolete version comparator.
Fix some warnings related to nullable
=> General fixes

unturned/redist/OpenMod.Unturned.Redist.nuspec
Imagine getting paid for advertising an event which will happen in your game.
=> fix nuspec for redist update

unturned/OpenMod.Unturned/Locations/UnturnedLocation.cs, unturned/OpenMod.Unturned/Locations/UnturnedLocationCommandParameterResolveProvider.cs, unturned/OpenMod.Unturned/Locations/UnturnedLocationDirectory.cs
=> Fix `IUnturnedLocationDirectory.GetLocations` returns nothing

.github/workflows/codeql-analysis.yaml
=> Ignore codeql analysis in docs directory

framework/OpenMod.API/Plugins/IPluginServiceConfigurationContext.cs, framework/OpenMod.Core/Plugins/PluginActivator.cs, framework/OpenMod.Core/Plugins/PluginServiceConfigurationContext.cs
=> Add WorkingDirectory in IPluginServiceConfigurationContext

standalone/OpenMod.Standalone/OpenMod.Standalone.csproj
=> Bug fix in standalone when unable to load required assembly

templates/templates/unturned/.template.config/template.json
sorry if I did something wrong t-t
=> Fix typo in template.json

framework/OpenMod.Core/Commands/AsyncLocalCurrentCommandContextAccessor.cs
This is prework for https://github.com/openmod/openmod/issues/648
=> Use AsyncLocal for storing current command context

framework/OpenMod.Core/Helpers/SmartFormatterHelper.cs, framework/OpenMod.Core/Localization/ConfigurationBasedStringLocalizer.cs, framework/OpenMod.Core/Localization/ConfigurationBasedStringLocalizerFactory.cs, framework/OpenMod.Core/Localization/SmartFormatOptions.cs, framework/OpenMod.Core/ServiceConfigurator.cs, framework/OpenMod.Runtime/OpenModHostedService.cs
RFC. Now, to get the `SmartFormatter` it needs to inject `IOptions<SmartFormatOption>` and use `GetSmartFormatter()` method.
Or create another service `ISmartFormatterAccessor` to get `SmartFormatter`, but still requires the `IOptions` to configure it.
=> Make SmartFormatter to be configurable via IOption

unturned/OpenMod.Unturned/Vehicles/UnturnedVehicleSpawner.cs, unturned/OpenMod.Unturned/Vehicles/UnturnedVehicleState.cs
Now it's includes the version of vehicle state data and item battery GUID.
=> Update the serialization of vehicle state

unturned/OpenMod.Unturned/Players/Stats/Events/PlayerStatsEventsListener.cs
=> Replace PlayerLife.OnTellVirus_Global with PlayerLife.onVirusUpdated

unturned/OpenMod.Unturned/Animals/Events/AnimalsEventsListener.cs
=> Fixed exception at patching Animal.alertPlayer(Player potentialTargetPlayer, bool sendToPack)

unturned/OpenMod.Unturned/Events/UnturnedEventsListener.cs, unturned/OpenMod.Unturned/Events/UnturnedPlayerEventsListener.cs, unturned/OpenMod.Unturned/OpenMod.Unturned.csproj, unturned/OpenMod.Unturned/Players/Equipment/Events/PlayerEquipmentEventsListener.cs, unturned/OpenMod.Unturned/Players/Input/Events/PlayerInputEventsListener.cs, unturned/OpenMod.Unturned/Players/Inventory/Events/PlayerInventoryEventsListener.cs, unturned/OpenMod.Unturned/Players/Life/Events/PlayerLifeEventsListener.cs, unturned/OpenMod.Unturned/Players/Movement/Events/PlayerMovementEventsListener.cs, unturned/OpenMod.Unturned/Players/Quests/Events/PlayerQuestsEventsListener.cs, unturned/OpenMod.Unturned/Players/Stats/Events/PlayerStatsEventsListener.cs, unturned/OpenMod.Unturned/Players/Voice/Events/PlayerVoiceEventsListener.cs
Unsubscription doesn't work when using lambdas this way.
=> Fix event listeners improperly unsubscribe from player events

unturned/OpenMod.Unturned/Players/Input/Events/PlayerInputEventsListener.cs
=> Fix OnPluginKeyTick throws KeyNotFoundException

docs/userdoc/concepts/jobs.md
Updating documentation after #795
=> Update `jobs` user documentation 

unturned/OpenMod.Unturned/Players/Inventory/Events/PlayerInventoryEventsListener.cs, unturned/OpenMod.Unturned/Players/Life/Events/PlayerLifeEventsListener.cs, unturned/OpenMod.Unturned/Players/Quests/Events/PlayerQuestsEventsListener.cs, unturned/OpenMod.Unturned/Players/Quests/Events/UnturnedPlayerGroupChangedEvent.cs, unturned/OpenMod.Unturned/Players/Quests/Events/UnturnedPlayerGroupIdChangedEvent.cs, unturned/OpenMod.Unturned/Players/Quests/Events/UnturnedPlayerGroupOrRankChangedEvent.cs, unturned/OpenMod.Unturned/Players/Quests/Events/UnturnedPlayerJoiningGroupEvent.cs, unturned/OpenMod.Unturned/Players/Quests/Events/UnturnedPlayerLeavingGroupEvent.cs
=> Events on player joining/leaving group

.editorconfig, OpenMod.sln, framework/OpenMod.API/Jobs/IJobScheduler.cs, framework/OpenMod.API/Jobs/ITaskExecutor.cs, framework/OpenMod.API/Jobs/JobCreationParameters.cs, framework/OpenMod.API/Jobs/JobTask.cs, framework/OpenMod.API/Jobs/KnownJobTypes.cs, framework/OpenMod.API/Jobs/ScheduledJob.cs, framework/OpenMod.API/Persistence/SerializeIgnoreAttribute.cs, framework/OpenMod.Core/Helpers/AsyncHelper.cs, framework/OpenMod.Core/Jobs/CommandTaskExecutor.cs, framework/OpenMod.Core/Jobs/JobExecutorOptions.cs, framework/OpenMod.Core/Jobs/JobScheduler.cs, framework/OpenMod.Core/Jobs/OpenModCommandTaskExecutor.cs, framework/OpenMod.Core/Jobs/SystemCommandTaskExecutor.cs, framework/OpenMod.Core/Persistence/YamlDataStore.cs, framework/OpenMod.Core/autoexec.yaml, unturned/OpenMod.Unturned/Commands/UnturnedBuiltinCommand.cs, unturned/OpenMod.Unturned/Commands/UnturnedCommandSource.cs
=> Fix job scheduler

unturned/OpenMod.Unturned/Players/Stats/Events/PlayerStatsEventsListener.cs
Open an issue at [#4373](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/4373) related to this event
=> Fix virus updated

.github/workflows/codeql-analysis.yaml, OpenMod.sln, extensions/OpenMod.Extensions.Games.Abstractions/Items/ItemDirectoryExtensions.cs, framework/OpenMod.Core/Jobs/JobScheduler.cs, unturned/OpenMod.Unturned/Mono/Patch_SocketTaskExtensions.cs
- Fix job racing condition
- Fix MinBy being deprecated
- Fix CodeQL autobuild
=> Fix jobs racing condition

unturned/OpenMod.Unturned/Vehicles/Events/VehicleEventsListener.cs
=> Fix ambiguous match in patch for VehicleManager.SpawnVehicleV3

.github/workflows/OpenMod.API.yaml, .github/workflows/OpenMod.Analyzers.yaml, .github/workflows/OpenMod.Bootstrapper.yaml, .github/workflows/OpenMod.Common.yaml, .github/workflows/OpenMod.Core.yaml, .github/workflows/OpenMod.EntityFrameworkCore.MySql.yaml, .github/workflows/OpenMod.EntityFrameworkCore.yaml, .github/workflows/OpenMod.Extensions.Economy.Abstractions.yaml, .github/workflows/OpenMod.Extensions.Games.Abstractions.yaml, .github/workflows/OpenMod.NuGet.yaml, .github/workflows/OpenMod.Release.yaml, .github/workflows/OpenMod.Runtime.yaml, .github/workflows/OpenMod.Rust.Oxide.Extension.yaml, .github/workflows/OpenMod.Rust.Oxide.PermissionLink.yaml, .github/workflows/OpenMod.Rust.Oxide.Redist.yaml, .github/workflows/OpenMod.Rust.Oxide.yaml, .github/workflows/OpenMod.Rust.Redist.yaml, .github/workflows/OpenMod.Rust.yaml, .github/workflows/OpenMod.Standalone.yaml, .github/workflows/OpenMod.Templates.yaml, .github/workflows/OpenMod.UniTask.yaml, .github/workflows/OpenMod.UnityEngine.Redist.yaml, .github/workflows/OpenMod.UnityEngine.yaml, .github/workflows/OpenMod.Unturned.Module.yaml, .github/workflows/OpenMod.Unturned.Redist.yaml, .github/workflows/OpenMod.Unturned.yaml, .github/workflows/documentation.yaml
=> Update action versions in workflows

unturned/redist/OpenMod.Unturned.Redist.nuspec
Updated Unturned.Redist package version to reflect Unturned runtime version from previous PR
=> Updated Unturned.Redist package version
